### ISSUE TITLE
Rocket-nginx works with Plesk 12.5 Nginx FPM php 7.0.13

### ISSUE THREAD

**Issue by rudy788** [maximejobin/rocket-nginx#44] opened 2016-12-01 09:00 UTC
Hi, I need an nginx configuration additional directives to use with Plesk and FPM nginx. I hope you can do it for all webmaster that use this environment.
Thank you, rudy.

**Comment by rudy788** [comment] 2016-12-01 10:54
If I add your nginx.conf file in additional directives works all except this part:`# Add header to HTML cached files
location ~ /#!# WP_CONTENT_URI #!#/cache/wp-rocket/.*html$ {
	etag on;
	add_header Vary "Accept-Encoding, Cookie";
	add_header Cache-Control "no-cache";
	add_header X-Rocket-Nginx-Bypass $rocket_is_bypassed;
	add_header X-Rocket-Nginx-Reason $rocket_reason;
	add_header X-Rocket-Nginx-File $rocket_file;
	
	
	#!# HEADER_HTTP #!#
	#!# HEADER_NON_GZIP #!#
}

# Do not gzip cached files that are already gzipped
location ~ /#!# WP_CONTENT_URI #!#/cache/wp-rocket/.*_gzip$ {
	etag on;
	gzip off;
	types {}
	default_type text/html;
	add_header Content-Encoding gzip;
	add_header Vary "Accept-Encoding, Cookie";
	add_header X-Rocket-Nginx-Bypass $rocket_is_bypassed;
	add_header X-Rocket-Nginx-Reason $rocket_reason;
	add_header X-Rocket-Nginx-File $rocket_file;
	
	#!# HEADER_HTTP #!#
	#!# HEADER_GZIP #!#
}

# Debug header (when file is not cached)
add_header X-Rocket-Nginx-Bypass $rocket_is_bypassed;
add_header X-Rocket-Nginx-Reason $rocket_reason;
add_header X-Rocket-Nginx-File $rocket_file;

`

**Comment by rudy788** [comment] 2016-12-01 11:05
If I change:` location ~ /#!# WP_CONTENT_URI #!#/cache/wp-rocket/` with `location ~ /wp-content/cache/wp-rocket/` plesk doesn't give me any error.

**Comment by rudy788** [comment] 2016-12-01 11:37
So, I test all thing like you say in the FAQ. If you change the `#!# WP_CONTENT_URI #!#` and write `wp-content` all directives works fine on plesk 12.5 with nginx-fpm!
I have found a little bug when I do the debug `/var/www/vhosts/mywebsite.com/httpdocs/wp-content/cache/wp-rocket/www.magup.it///index-https.html_gzip` there are too many slashes.
Regards, Rudy.

**Comment by maximejobin** [comment] 2016-12-01 15:16
I'm now working on version 2.0 on this script and, for some reason, the version was merged by error into the master branch.

I just removed all the commits from version 2.0 in the master branch and it is back to version 1.2 (as it should).

I strongly suggest that you try the version 1.2 for now as the version you are using is incomplete and untested.

I'm truly sorry for that error.

**Comment by rudy788** [comment] 2016-12-01 15:21
ok, thank you.

**Comment by Excelautomation** [comment] 2017-04-19 08:21
Hi @maximejobin. May I ask what's the status for Plesk-support? I've using WP Rocket and Plesk 12.5 myself, and when I try pasting the wp-rocket configuration into the "additional nginx directives" I'm getting an "set"-error.

**Comment by maximejobin** [comment] 2017-04-19 15:50
I do this project as a volunteer because I love WP Rocket.

I unfortunately don't have a Plesk account.  Then, I would need someone to sponsor the testing so I can figure out how it can work properly and adjust the script.

If someone is interested to sponsor that, I will gladly do the necessary to make it happen. The thing is I have to many things on my plate right now that I cannot do it.  I hope you'll understand!

**Comment by Excelautomation** [comment] 2017-04-19 15:53
Actually I tried your earlier 1.2 version, and this seems to work just fine. Not quite sure why Plesk returned the "set" error. I think it was caused by the /#!# WP_CONTENT_URI #!#

**Comment by maximejobin** [comment] 2017-04-19 17:11
I don't know exactly what you did but if you updated from version 1.x to 2.0, see the Installation section:
https://github.com/maximejobin/rocket-nginx/tree/2.0#installation

It seems like you are using the template file.

**Comment by rudy788** [comment] 2017-04-20 08:01
Hi @maximejobin, can you make an nginx.conf static configuration in order to use simply for example in additional directives in plesk? Thank you.

**Comment by maximejobin** [comment] 2017-04-20 23:37
@rudy788 See [this comment](https://github.com/maximejobin/rocket-nginx/issues/44#issuecomment-295318757).

**Comment by mgmaik** [comment] 2017-06-24 15:13
I've generated the config on centos7 with plesk onyx but I get an error when I put the code in the "additional nginx directives" 

Here is the code that gives the error
`# Do not bypass if one of those cookie if found
# wordpress_logged_in_[hash] : When a user is logged in, this cookie is created (we'd rather let WP-Rocket handle that)
# wp-postpass_[hash] : When a protected post requires a password, this cookie is created.
if ($http_cookie ~* "(wordpress_logged_in_|wp\-postpass_|woocommerce_items_in_cart|woocommerce_cart_hash|wptouch_switch_toogle|comment_aut$
        set $rocket_bypass 0;
        set $rocket_reason "Cookie";
}`

If I delete that code the homepage works fine. But other pages images are not loading properly (I have wordpress pretty permalinks on)

**Comment by maximejobin** [comment] 2018-09-10 15:55
Are you using Nginx as a "Nginx-only" solution for Plesk or is it as reverse proxy ?

If you are using Nginx with Apache, Nginx is used as a reverse proxy. You DO NOT need Rocket-Nginx.

If you are using Nginx as a "Nginx-only" solution as [described here](https://docs.plesk.com/en-US/onyx/customer-guide/websites-and-domains/hosting-settings/web-server-settings/apache-and-nginx-settings/nginxonly-hosting.78407/), I would like to have access to an account to be able to fix the issue once and for all.

**Closed** 2018-10-23 14:39 UTC
Labels: help wanted
