### ISSUE TITLE
rocket-nginx + Plesk problem

### ISSUE THREAD

**Issue by maxx203** [maximejobin/rocket-nginx#60] opened 2017-08-01 18:31 UTC
Hello everyone,

since a few years iam using wp rocket with nginx. To allow that more then me in person can work and manage the server iam using plesk to simplify the hosting access. Currently iam using a very old version of your wo rocket nginx configuration which can be seen here: https://pastebin.com/FDUyHUWm

In the past weeks i tried to update the configuration as wp rocket suggest to do so but i only receive an error which iam not able to resolve. 

Invalid nginx configuration: nginx: [emerg] invalid number of arguments in "set" directive in /var/www/vhosts/system/battlefield-inside.de/conf/vhost_nginx.conf:34 nginx: configuration file /etc/nginx/nginx.conf test failed

Alice Orrù form wp rocket told me that i better have to ask here for any help.

Regards 
Maximilian

**Comment by maxx203** [comment] 2017-08-10 21:54
Any feedback here?

**Comment by maximejobin** [comment] 2017-08-10 23:35
You posted a modified version of Rocket-Nginx where you removed the copyright and the version number so it is hard to know what version you were using.

Also, you did not mention what you used to replace it. By seeing the updated code you are using, it increases the chances that I can help.

**Comment by maxx203** [comment] 2017-08-11 17:53
I want to use version 2.0. Currently iam using version 1.2.

**Comment by maximejobin** [comment] 2017-08-11 17:56
Ok, I get that. :-)

You showed me how you were using version 1.2. Can you show me the new file you are using that produce the error ? You did copy/paste in pastebin the old file that you are not using anymore. I would like to see the new file you are using, please.

**Comment by maximejobin** [comment] 2017-10-25 13:31
No news for more than 2 months so I'm closing this. Feel free to reopen if you have issues.

**Closed by maximejobin** 2017-10-25 13:31 UTC

**Comment by maxx203** [comment] 2017-10-25 14:42
Not noticed, that your replied. 

You wanted me to post you the old and new file 

Old: (currently in use)
https://pastebin.com/wp0rqS7b

New: (with error, not able to use)
https://pastebin.com/AnTj0qhe

The error is:

Invalid nginx configuration: nginx: [emerg] unexpected ";" in /var/www/vhosts/system/battlefield-inside.de/conf/vhost_nginx.conf:12 nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by maximejobin** [comment] 2017-10-26 14:09
The problem is simple: you copied the "ini" file in your configuration.

Please follow the steps found here: https://github.com/maximejobin/rocket-nginx#configuration

Once you have run the parser, it will create a `.conf` file. You must take the content of this file and paste it in your configuration.

**Comment by maxx203** [comment] 2017-10-26 16:19
Within Plesk Adminpanel everything is way different. I can not generate anything here as this will have issues to futher operate the Plesk Webserver and all sites will be offline.
